# ===================================================================
# PRODUCTION SETTINGS - POSTGRESQL (Profile: prod)
# ===================================================================
# Render will inject the database URL into this variable automatically
spring.datasource.url=jdbc:postgresql://${DB_HOST:dpg-d8jn8ps2m8qs739a1250-a.render.com}:5432/${DB_NAME:taskmanager_eyu3}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:g4lqTk7FtaScU3gmq8bP5iTHwRDsQHsh}
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Official PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate will create/update tables in Render's Postgres
spring.jpa.hibernate.ddl-auto=update

# Render defines the port dynamically through the PORT variable
server.port=${PORT:8080}

# Display formatted SQL logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true