# ===================================================================
# LOCAL CONFIGURATION - SQLITE (Profile: dev)
# ===================================================================
spring.datasource.url=jdbc:sqlite:taskmanager.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite Dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Automatic local database updates
spring.jpa.hibernate.ddl-auto=update

# Default local port
server.port=8080

# Display SQL logs
spring.jpa.show-sql=true