spring.datasource.url=jdbc:postgresql://${DB_HOST:dpg-d8jn8ps2m8qs739a1250-a.render.com}:5432/${DB_NAME:taskmanager_eyu3}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:g4lqTk7FtaScU3gmq8bP5iTHwRDsQHsh}
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.profiles.active=dev

#  SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# ddl-auto=update faz Java Build
spring.jpa.hibernate.ddl-auto=update

#server.port=8080
server.port=${PORT:8080}

# Optional: Show Console SQL Queries
spring.jpa.show-sql=true