# Settings DataBase SQLite
spring.datasource.url=jdbc:sqlite:taskmanager.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#  SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# ddl-auto=update faz Java Build
spring.jpa.hibernate.ddl-auto=update

# Optional: Show Console SQL Queries
spring.jpa.show-sql=true